module.exports = {
    SAVING_ERROR: {
        message: 'SAVING ERROR OCCURED',
        code:'SAVING ERROR OCCURED'
    },
    VALIDATE_TABLE_ERROR: {
        message: 'DATABASE ERROR OCCURED',
        code:'DATABASE ERROR OCCURED'
    },
    RECORD_NOT_FOUND: {
        message: 'THIS_RECORD_NOT_EXISTS',
        code: 'THIS_RECORD_NOT_FOUND'
    },
    RECORD_UPDATE_ERROR: {
        message: 'RECORD_UPDATE_ERROR',
        code: 'RECORD_UPDATE_ERROR'
    },
    MYSQL_SYNTAX_ERROR: {
        message: 'MYSQL_QUERY_SYNTAX_ERROR_PLEASE_CHECK_YOUR_QUERY',
        code: 'MYSQL_QUERY_SYNTAX_ERROR_PLEASE_CHECK_YOUR_QUERY'
    },
    SELECT_QUERY_PARAMS_LENGTH_IS_NOT_VALIED: {
        message: 'MYSQL_QUERY_SYNTAX_ERROR : SELECT_QUERY_REQUIRES_1_PARAM',
        code: 'MYSQL_QUERY_SYNTAX_ERROR : SELECT_QUERY_REQUIRES_1_PARAM'
    }
}